### ISSUE TITLE
data source for aws_ami ubuntu cannot return results

### ISSUE THREAD

**Issue by BradleyYeo** [hashicorp/learn-terraform-state#13]
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_ami.ubuntu,
│   on main.tf line 5, in data "aws_ami" "ubuntu":
│    5: data "aws_ami" "ubuntu" {

**Comment by BrianMMcClain** [comment]
Hi @BradleyYeo! Thanks for raising this issue! I'm actually not able to reproduce this locally, could you provide some additional information on your environment, specifically if you specified a custom value for the `aws_region` variable or any changes made to the AWS `provider` block? Thanks!

**Comment by BradleyYeo** [comment]
It works when I tried it today, mistake must have been caused when I changed the value in owners, thank you

**Comment by BrianMMcClain** [comment]
Happy to hear you were able to resolve the issue! I'll go ahead and mark this as resolved :)
